declare type Produit = any;
declare type Boutique = any;
declare type Categorie = any;
declare type ClientDetailed = any;
declare type Creance = any;
declare type Demande = any;
declare type LigneProduitCreance = any;
declare type PaiementCreance = any;
declare type StockEnriched = any;
declare type UtilisateurItem = any;
declare type Vente = any;
declare type HistoriqueItem = any;
declare type Screen = any;
declare const formatMontant: any;
declare const DEFAULT_BOUTIQUE_ID: any;
declare const VENTES_SEMAINE: any;
declare const TOP_PRODUITS: any;
declare const CATEGORIES_DATA: any;
